### ISSUE TITLE
How to make custom one (the car plate detection model) to tensorrt?

### ISSUE THREAD

**Issue by edwardchang0112-nctu** [theAIGuysCode/yolov4-custom-functions#72]
I followed the instructions on the post 
The steps:
```
python3 save_model.py --weights ./data/custom.weights --output ./checkpoints/custom.tf --input_size 416 --model yolov4
python3 convert_trt.py --weights ./checkpoints/custom.tf --quantize_mode float16 --output ./checkpoints/custom-trt-fp16-416
```
but got the error:
```
Traceback (most recent call last):
  File "convert_trt.py", line 100, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "convert_trt.py", line 96, in main
    save_trt()
  File "convert_trt.py", line 58, in save_trt
    max_batch_size=8)
  File "<string>", line 28, in _replace
ValueError: Got unexpected field names: ['max_batch_size']
```
Any idea on this issue?

**Comment by animeesh** [comment]
i got the same. do let me know if you got the solution

**Comment by farshokat** [comment]
i need your answer, thanks
