### ISSUE TITLE
Cannot convert yolov4-tiny custom model (Please help)

### ISSUE THREAD

**Issue by asdsdk** [theAIGuysCode/yolov4-custom-functions#75]
2022-01-20 07:59:48.974393: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
Traceback (most recent call last):
  File "save_model.py", line 58, in <module>
    app.run(main)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 54, in main
    save_tf()
  File "save_model.py", line 49, in save_tf
    utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
  File "/content/yolov4-custom-functions/core/utils.py", line 143, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 767781 into shape (256,384,3,3)

**Comment by asdsdk** [comment]
This is my command

!python save_model.py --weights ./data/yolov3-tiny_best.weights --output ./checkpoints/yolov3-tiny-416 --input_size 416 --model yolov3  --tiny

**Comment by DrZaiius** [comment]
what was the issue? it happens to me exactly the same array size
